"use client";
import { ChainContext } from "@/context/ChainContext";
import Header from "../../components/custom/Header";
import ApolloProvider from "../apollo/ApolloProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Everscale-explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChainContext>
          <ApolloProvider>
            <main className="flex px-2 md:px-8 min-h-screen flex-col ">
              <Header />
              {children}
            </main>
          </ApolloProvider>
        </ChainContext>
      </body>
    </html>
  );
}
